# nixpacks.toml — Railway build configuration for License Server
# Server only needs FastAPI + PostgreSQL, NO Playwright/Chromium needed here.

[phases.setup]
nixPkgs = ["python3Packages.pip"]

[phases.install]
cmds = [
    "pip install -r server/requirements.txt",
]
